package com.ind.mod.datagenerator;

import com.ind.mod.StoneWoodIndustry;
import com.ind.mod.block.ModBlocks;
import com.ind.mod.enchantment.ModEnchantment;
import com.ind.mod.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.util.Identifier;

public class EnUsLanguageGenerator extends FabricLanguageProvider {
    public EnUsLanguageGenerator(FabricDataOutput dataOutput) {
        super(dataOutput);
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModBlocks.SMOOTH_STONE_PRESSURE_PLATE, "Smooth Stone Pressure Plate");
        translationBuilder.add(ModBlocks.SMOOTH_STONE_STAIRS, "Smooth Stone Stairs");
        translationBuilder.add(ModBlocks.SMOOTH_STONE_BUTTON, "Smooth Stone Button");
        translationBuilder.add(ModItems.STONE_HELMET, "Stone Helmet");
        translationBuilder.add(ModItems.STONE_CHESTPLATE, "Stone Chestplate");
        translationBuilder.add(ModItems.STONE_LEGGINGS, "Stone Leggings");
        translationBuilder.add(ModItems.STONE_BOOTS, "Stone Boots");
        translationBuilder.add(ModItems.SMOOTH_STONE_HELMET, "Smooth Stone Helmet");
        translationBuilder.add(ModItems.SMOOTH_STONE_CHESTPLATE, "Smooth Stone Chestplate");
        translationBuilder.add(ModItems.SMOOTH_STONE_LEGGINGS, "Smooth Stone Leggings");
        translationBuilder.add(ModItems.SMOOTH_STONE_BOOTS, "Smooth Stone Boots");
        translationBuilder.add(ModItems.SMOOTH_STONE_PICKAXE, "Smooth Stone Pickaxe");
        translationBuilder.add(ModItems.SMOOTH_STONE_AXE, "Smooth Stone Axe");
        translationBuilder.add(ModItems.SMOOTH_STONE_HOE, "Smooth Stone Hoe");
        translationBuilder.add(ModItems.SMOOTH_STONE_SHOVEL, "Smooth Stone Shovel");
        translationBuilder.add(ModItems.SMOOTH_STONE_SWORD, "Smooth Stone Sword");
        translationBuilder.add(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_stone"), "Stone Wood Industry: Stone Products");
        translationBuilder.add(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_wood"), "Stone Wood Industry: Wood Products");
        translationBuilder.add(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_enchant"), "Stone Wood Industry: Enchantment");
        translationBuilder.add(ModItems.OAK_HELMET, "Oak Helmet");
        translationBuilder.add(ModItems.OAK_CHESTPLATE, "Oak Chestplate");
        translationBuilder.add(ModItems.OAK_LEGGINGS, "Oak Leggings");
        translationBuilder.add(ModItems.OAK_BOOTS, "Oak Boots");
        translationBuilder.add(ModItems.BIRCH_HELMET, "Birch Helmet");
        translationBuilder.add(ModItems.BIRCH_CHESTPLATE, "Birch Chestplate");
        translationBuilder.add(ModItems.BIRCH_LEGGINGS, "Birch Leggings");
        translationBuilder.add(ModItems.BIRCH_BOOTS, "Birch Boots");
        translationBuilder.add(ModItems.SPRUCE_HELMET, "Spruce Helmet");
        translationBuilder.add(ModItems.SPRUCE_CHESTPLATE, "Spruce Chestplate");
        translationBuilder.add(ModItems.SPRUCE_LEGGINGS, "Spruce Leggings");
        translationBuilder.add(ModItems.SPRUCE_BOOTS, "Spruce Boots");
        translationBuilder.add(ModItems.JUNGLE_HELMET, "Jungle Helmet");
        translationBuilder.add(ModItems.JUNGLE_CHESTPLATE, "Jungle Chestplate");
        translationBuilder.add(ModItems.JUNGLE_LEGGINGS, "Jungle Leggings");
        translationBuilder.add(ModItems.JUNGLE_BOOTS, "Jungle Boots");
        translationBuilder.add(ModItems.ACACIA_HELMET, "Acacia Helmet");
        translationBuilder.add(ModItems.ACACIA_CHESTPLATE, "Acacia Chestplate");
        translationBuilder.add(ModItems.ACACIA_LEGGINGS, "Acacia Leggings");
        translationBuilder.add(ModItems.ACACIA_BOOTS, "Acacia Boots");
        translationBuilder.add(ModItems.DARK_OAK_HELMET, "Dark Oak Helmet");
        translationBuilder.add(ModItems.DARK_OAK_CHESTPLATE, "Dark Oak Chestplate");
        translationBuilder.add(ModItems.DARK_OAK_LEGGINGS, "Dark Oak Leggings");
        translationBuilder.add(ModItems.DARK_OAK_BOOTS, "Dark Oak Boots");
        translationBuilder.add(ModItems.MANGROVE_HELMET, "Mangrove Helmet");
        translationBuilder.add(ModItems.MANGROVE_CHESTPLATE, "Mangrove Chestplate");
        translationBuilder.add(ModItems.MANGROVE_LEGGINGS, "Mangrove Leggings");
        translationBuilder.add(ModItems.MANGROVE_BOOTS, "Mangrove Boots");
        translationBuilder.add(ModItems.CHERRY_HELMET, "Cherry Helmet");
        translationBuilder.add(ModItems.CHERRY_CHESTPLATE, "Cherry Chestplate");
        translationBuilder.add(ModItems.CHERRY_LEGGINGS, "Cherry Leggings");
        translationBuilder.add(ModItems.CHERRY_BOOTS, "Cherry Boots");
        translationBuilder.add(ModItems.BLACKSTONE_HELMET, "Blackstone Helmet");
        translationBuilder.add(ModItems.BLACKSTONE_CHESTPLATE, "Blackstone Chestplate");
        translationBuilder.add(ModItems.BLACKSTONE_LEGGINGS, "Blackstone Leggings");
        translationBuilder.add(ModItems.BLACKSTONE_BOOTS, "Blackstone Boots");
        translationBuilder.add(ModItems.DEEPSLATE_HELMET, "Deepslate Helmet");
        translationBuilder.add(ModItems.DEEPSLATE_CHESTPLATE, "Deepslate Chestplate");
        translationBuilder.add(ModItems.DEEPSLATE_LEGGINGS, "Deepslate Leggings");
        translationBuilder.add(ModItems.DEEPSLATE_BOOTS, "Deepslate Boots");
        translationBuilder.add(ModItems.BAMBOO_HELMET, "Bamboo Helmet");
        translationBuilder.add(ModItems.BAMBOO_CHESTPLATE, "Bamboo Chestplate");
        translationBuilder.add(ModItems.BAMBOO_LEGGINGS, "Bamboo Leggings");
        translationBuilder.add(ModItems.BAMBOO_BOOTS, "Bamboo Boots");
        translationBuilder.add(ModItems.CRIMSON_HELMET, "Crimson Helmet");
        translationBuilder.add(ModItems.CRIMSON_CHESTPLATE, "Crimson Chestplate");
        translationBuilder.add(ModItems.CRIMSON_LEGGINGS, "Crimson Leggings");
        translationBuilder.add(ModItems.CRIMSON_BOOTS, "Crimson Boots");
        translationBuilder.add(ModItems.WARPED_HELMET, "Warped Helmet");
        translationBuilder.add(ModItems.WARPED_CHESTPLATE, "Warped Chestplate");
        translationBuilder.add(ModItems.WARPED_LEGGINGS, "Warped Leggings");
        translationBuilder.add(ModItems.WARPED_BOOTS, "Warped Boots");
        translationBuilder.add(ModItems.NETHERRACK_HELMET, "Dark Oak Helmet");
        translationBuilder.add(ModItems.NETHERRACK_CHESTPLATE, "Dark Oak Chestplate");
        translationBuilder.add(ModItems.NETHERRACK_LEGGINGS, "Dark Oak Leggings");
        translationBuilder.add(ModItems.NETHERRACK_BOOTS, "Dark Oak Boots");
        translationBuilder.add(ModItems.BASALT_HELMET, "Mangrove Helmet");
        translationBuilder.add(ModItems.BASALT_CHESTPLATE, "Mangrove Chestplate");
        translationBuilder.add(ModItems.BASALT_LEGGINGS, "Mangrove Leggings");
        translationBuilder.add(ModItems.BASALT_BOOTS, "Mangrove Boots");
        translationBuilder.add(ModItems.END_STONE_HELMET, "End Stone Helmet");
        translationBuilder.add(ModItems.END_STONE_CHESTPLATE, "End Stone Chestplate");
        translationBuilder.add(ModItems.END_STONE_LEGGINGS, "End Stone Leggings");
        translationBuilder.add(ModItems.END_STONE_BOOTS, "End Stone Boots");
        translationBuilder.add(ModItems.DIORITE_HELMET, "Diorite Helmet");
        translationBuilder.add(ModItems.DIORITE_CHESTPLATE, "Diorite Chestplate");
        translationBuilder.add(ModItems.DIORITE_LEGGINGS, "Diorite Leggings");
        translationBuilder.add(ModItems.DIORITE_BOOTS, "Diorite Boots");
        translationBuilder.add(ModItems.GRANITE_HELMET, "Granite Helmet");
        translationBuilder.add(ModItems.GRANITE_CHESTPLATE, "Granite Chestplate");
        translationBuilder.add(ModItems.GRANITE_LEGGINGS, "Granite Leggings");
        translationBuilder.add(ModItems.GRANITE_BOOTS, "Granite Boots");
        translationBuilder.add(ModItems.ANDESITE_HELMET, "Andsite Helmet");
        translationBuilder.add(ModItems.ANDESITE_CHESTPLATE, "Andsite Chestplate");
        translationBuilder.add(ModItems.ANDESITE_LEGGINGS, "Andsite Leggings");
        translationBuilder.add(ModItems.ANDESITE_BOOTS, "Andsite Boots");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_HELMET, "Crying Obsidian Helmet");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_CHESTPLATE, "Crying Obsidian Chestplate");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_LEGGINGS, "Crying Obsidian Leggings");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_BOOTS, "Crying Obsidian Boots");
        translationBuilder.add(ModItems.OBSIDIAN_HELMET, "Obsidian Helmet");
        translationBuilder.add(ModItems.OBSIDIAN_CHESTPLATE, "Obsidian Chestplate");
        translationBuilder.add(ModItems.OBSIDIAN_LEGGINGS, "Obsidian Leggings");
        translationBuilder.add(ModItems.OBSIDIAN_BOOTS, "Obsidian Boots");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_PICKAXE, "Crying Obsidian Pickaxe");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_AXE, "Crying Obsidian Axe");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_HOE, "Crying Obsidian Hoe");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_SHOVEL, "Crying Obsidian Shovel");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_SWORD, "Crying Obsidian Sword");
        translationBuilder.add(ModItems.OBSIDIAN_PICKAXE, "Obsidian Pickaxe");
        translationBuilder.add(ModItems.OBSIDIAN_AXE, "Obsidian Axe");
        translationBuilder.add(ModItems.OBSIDIAN_HOE, "Obsidian Hoe");
        translationBuilder.add(ModItems.OBSIDIAN_SHOVEL, "Obsidian Shovel");
        translationBuilder.add(ModItems.OBSIDIAN_SWORD, "Obsidian Sword");
        translationBuilder.add(ModItems.END_STONE_PICKAXE, "End Stone Pickaxe");
        translationBuilder.add(ModItems.END_STONE_AXE, "End Stone Axe");
        translationBuilder.add(ModItems.END_STONE_HOE, "End Stone Hoe");
        translationBuilder.add(ModItems.END_STONE_SHOVEL, "End Stone Shovel");
        translationBuilder.add(ModItems.END_STONE_SWORD, "End Stone Sword");
        translationBuilder.add(ModEnchantment.HARDEN, "Harden");
        translationBuilder.add(ModEnchantment.SPEED, "Speed");
        translationBuilder.add(ModBlocks.OBSIDIAN_STAIRS, "Obsidian Stairs");
        translationBuilder.add(ModBlocks.OBSIDIAN_SLAB, "Obsidian Slab");
        translationBuilder.add(ModItems.BLACKSTONE_PICKAXE, "Blackstone Pickaxe");
        translationBuilder.add(ModItems.BLACKSTONE_AXE, "Blackstone Axe");
        translationBuilder.add(ModItems.BLACKSTONE_HOE, "Blackstone Hoe");
        translationBuilder.add(ModItems.BLACKSTONE_SHOVEL, "Blackstone Shovel");
        translationBuilder.add(ModItems.BLACKSTONE_SWORD, "Blackstone Sword");
        translationBuilder.add(ModItems.DEEPSLATE_PICKAXE, "Deepslate Pickaxe");
        translationBuilder.add(ModItems.DEEPSLATE_AXE, "Deepslate Axe");
        translationBuilder.add(ModItems.DEEPSLATE_HOE, "Deepslate Hoe");
        translationBuilder.add(ModItems.DEEPSLATE_SHOVEL, "Deepslate Shovel");
        translationBuilder.add(ModItems.DEEPSLATE_SWORD, "Deepslate Sword");
        translationBuilder.add(ModItems.NETHERRACK_PICKAXE, "Netherrack Pickaxe");
        translationBuilder.add(ModItems.NETHERRACK_AXE, "Netherrack Axe");
        translationBuilder.add(ModItems.NETHERRACK_HOE, "Netherrack Hoe");
        translationBuilder.add(ModItems.NETHERRACK_SHOVEL, "Netherrack Shovel");
        translationBuilder.add(ModItems.NETHERRACK_SWORD, "Netherrack Sword");
        translationBuilder.add(ModItems.DIORITE_PICKAXE, "Diorite Pickaxe");
        translationBuilder.add(ModItems.DIORITE_AXE, "Diorite Axe");
        translationBuilder.add(ModItems.DIORITE_HOE, "Diorite Hoe");
        translationBuilder.add(ModItems.DIORITE_SHOVEL, "Diorite Shovel");
        translationBuilder.add(ModItems.DIORITE_SWORD, "Diorite Sword");
        translationBuilder.add(ModItems.GRANITE_PICKAXE, "Granite Pickaxe");
        translationBuilder.add(ModItems.GRANITE_AXE, "Granite Axe");
        translationBuilder.add(ModItems.GRANITE_HOE, "Granite Hoe");
        translationBuilder.add(ModItems.GRANITE_SHOVEL, "Granite Shovel");
        translationBuilder.add(ModItems.GRANITE_SWORD, "Granite Sword");
        translationBuilder.add(ModItems.ANDESITE_PICKAXE, "Andesite Pickaxe");
        translationBuilder.add(ModItems.ANDESITE_AXE, "Andesite Axe");
        translationBuilder.add(ModItems.ANDESITE_HOE, "Andesite Hoe");
        translationBuilder.add(ModItems.ANDESITE_SHOVEL, "Andesite Shovel");
        translationBuilder.add(ModItems.ANDESITE_SWORD, "Andesite Sword");
        translationBuilder.add(ModItems.BASALT_PICKAXE, "Basalt Pickaxe");
        translationBuilder.add(ModItems.BASALT_AXE, "Basalt Axe");
        translationBuilder.add(ModItems.BASALT_HOE, "Basalt Hoe");
        translationBuilder.add(ModItems.BASALT_SHOVEL, "Basalt Shovel");
        translationBuilder.add(ModItems.BASALT_SWORD, "Basalt Sword");
    }
}
