package com.ind.mod.datagenerator;

import com.ind.mod.StoneWoodIndustry;
import com.ind.mod.block.ModBlocks;
import com.ind.mod.item.ModItems;
import net.fabricmc.fabric.api.datagen.v1.FabricDataOutput;
import net.fabricmc.fabric.api.datagen.v1.provider.FabricLanguageProvider;
import net.minecraft.util.Identifier;

public class ZhCnLanguageGenerator extends FabricLanguageProvider {
    public ZhCnLanguageGenerator(FabricDataOutput dataOutput) {
        super(dataOutput, "zh_cn");
    }

    @Override
    public void generateTranslations(TranslationBuilder translationBuilder) {
        translationBuilder.add(ModBlocks.SMOOTH_STONE_PRESSURE_PLATE, "平滑石压力板");
        translationBuilder.add(ModBlocks.SMOOTH_STONE_STAIRS, "平滑石楼梯");
        translationBuilder.add(ModBlocks.SMOOTH_STONE_BUTTON, "平滑石按钮");
        translationBuilder.add(ModItems.STONE_HELMET, "石头头盔");
        translationBuilder.add(ModItems.STONE_CHESTPLATE, "石头胸甲");
        translationBuilder.add(ModItems.STONE_LEGGINGS, "石头护腿");
        translationBuilder.add(ModItems.STONE_BOOTS, "石头靴子");
        translationBuilder.add(ModItems.SMOOTH_STONE_HELMET, "平滑石头盔");
        translationBuilder.add(ModItems.SMOOTH_STONE_CHESTPLATE, "平滑石胸甲");
        translationBuilder.add(ModItems.SMOOTH_STONE_LEGGINGS, "平滑石护腿");
        translationBuilder.add(ModItems.SMOOTH_STONE_BOOTS, "平滑石靴子");
        translationBuilder.add(ModItems.SMOOTH_STONE_PICKAXE, "平滑石镐子");
        translationBuilder.add(ModItems.SMOOTH_STONE_AXE, "平滑石斧头");
        translationBuilder.add(ModItems.SMOOTH_STONE_HOE, "平滑石锄头");
        translationBuilder.add(ModItems.SMOOTH_STONE_SHOVEL, "平滑石铲子");
        translationBuilder.add(ModItems.SMOOTH_STONE_SWORD, "平滑石剑");
        translationBuilder.add(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_stone"), "石木工艺：石头制品");
        translationBuilder.add(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_wood"), "石木工艺：木头制品");
        translationBuilder.add(ModItems.OAK_HELMET, "橡木头盔");
        translationBuilder.add(ModItems.OAK_CHESTPLATE, "橡木胸甲");
        translationBuilder.add(ModItems.OAK_LEGGINGS, "橡木护腿");
        translationBuilder.add(ModItems.OAK_BOOTS, "橡木鞋子");
        translationBuilder.add(ModItems.BIRCH_HELMET, "白桦木头盔");
        translationBuilder.add(ModItems.BIRCH_CHESTPLATE, "白桦木胸甲");
        translationBuilder.add(ModItems.BIRCH_LEGGINGS, "白桦木护腿");
        translationBuilder.add(ModItems.BIRCH_BOOTS, "白桦木鞋子");
        translationBuilder.add(ModItems.SPRUCE_HELMET, "云杉木头盔");
        translationBuilder.add(ModItems.SPRUCE_CHESTPLATE, "云杉木胸甲");
        translationBuilder.add(ModItems.SPRUCE_LEGGINGS, "云杉木护腿");
        translationBuilder.add(ModItems.SPRUCE_BOOTS, "云杉木鞋子");
        translationBuilder.add(ModItems.JUNGLE_HELMET, "丛林木头盔");
        translationBuilder.add(ModItems.JUNGLE_CHESTPLATE, "丛林木胸甲");
        translationBuilder.add(ModItems.JUNGLE_LEGGINGS, "丛林木护腿");
        translationBuilder.add(ModItems.JUNGLE_BOOTS, "丛林木鞋子");
        translationBuilder.add(ModItems.ACACIA_HELMET, "金合欢木头盔");
        translationBuilder.add(ModItems.ACACIA_CHESTPLATE, "金合欢木胸甲");
        translationBuilder.add(ModItems.ACACIA_LEGGINGS, "金合欢木护腿");
        translationBuilder.add(ModItems.ACACIA_BOOTS, "金合欢木鞋子");
        translationBuilder.add(ModItems.DARK_OAK_HELMET, "深色橡木头盔");
        translationBuilder.add(ModItems.DARK_OAK_CHESTPLATE, "深色橡木胸甲");
        translationBuilder.add(ModItems.DARK_OAK_LEGGINGS, "深色橡木护腿");
        translationBuilder.add(ModItems.DARK_OAK_BOOTS, "深色橡木鞋子");
        translationBuilder.add(ModItems.MANGROVE_HELMET, "红树头盔");
        translationBuilder.add(ModItems.MANGROVE_CHESTPLATE, "红树胸甲");
        translationBuilder.add(ModItems.MANGROVE_LEGGINGS, "红树护腿");
        translationBuilder.add(ModItems.MANGROVE_BOOTS, "红树鞋子");
        translationBuilder.add(ModItems.CHERRY_HELMET, "樱花木头盔");
        translationBuilder.add(ModItems.CHERRY_CHESTPLATE, "樱花木胸甲");
        translationBuilder.add(ModItems.CHERRY_LEGGINGS, "樱花木护腿");
        translationBuilder.add(ModItems.CHERRY_BOOTS, "樱花木鞋子");
        translationBuilder.add(ModItems.BLACKSTONE_HELMET, "黑石头盔");
        translationBuilder.add(ModItems.BLACKSTONE_CHESTPLATE, "黑石胸甲");
        translationBuilder.add(ModItems.BLACKSTONE_LEGGINGS, "黑石护腿");
        translationBuilder.add(ModItems.BLACKSTONE_BOOTS, "黑石鞋子");
        translationBuilder.add(ModItems.DEEPSLATE_HELMET, "深板岩头盔");
        translationBuilder.add(ModItems.DEEPSLATE_CHESTPLATE, "深板岩胸甲");
        translationBuilder.add(ModItems.DEEPSLATE_LEGGINGS, "深板岩护腿");
        translationBuilder.add(ModItems.DEEPSLATE_BOOTS, "深板岩鞋子");
        translationBuilder.add(ModItems.BAMBOO_HELMET, "竹子头盔");
        translationBuilder.add(ModItems.BAMBOO_CHESTPLATE, "竹子胸甲");
        translationBuilder.add(ModItems.BAMBOO_LEGGINGS, "竹子护腿");
        translationBuilder.add(ModItems.BAMBOO_BOOTS, "竹子鞋子");
        translationBuilder.add(ModItems.CRIMSON_HELMET, "绯红木头盔");
        translationBuilder.add(ModItems.CRIMSON_CHESTPLATE, "绯红木胸甲");
        translationBuilder.add(ModItems.CRIMSON_LEGGINGS, "绯红木护腿");
        translationBuilder.add(ModItems.CRIMSON_BOOTS, "绯红木鞋子");
        translationBuilder.add(ModItems.WARPED_HELMET, "诡异木头盔");
        translationBuilder.add(ModItems.WARPED_CHESTPLATE, "诡异木胸甲");
        translationBuilder.add(ModItems.WARPED_LEGGINGS, "诡异木护腿");
        translationBuilder.add(ModItems.WARPED_BOOTS, "诡异木鞋子");
        translationBuilder.add(ModItems.NETHERRACK_HELMET, "下界岩头盔");
        translationBuilder.add(ModItems.NETHERRACK_CHESTPLATE, "下界岩胸甲");
        translationBuilder.add(ModItems.NETHERRACK_LEGGINGS, "下界岩护腿");
        translationBuilder.add(ModItems.NETHERRACK_BOOTS, "下界岩鞋子");
        translationBuilder.add(ModItems.BASALT_HELMET, "玄武岩头盔");
        translationBuilder.add(ModItems.BASALT_CHESTPLATE, "玄武岩胸甲");
        translationBuilder.add(ModItems.BASALT_LEGGINGS, "玄武岩护腿");
        translationBuilder.add(ModItems.BASALT_BOOTS, "玄武岩鞋子");
        translationBuilder.add(ModItems.END_STONE_HELMET, "末地石头盔");
        translationBuilder.add(ModItems.END_STONE_CHESTPLATE, "末地石胸甲");
        translationBuilder.add(ModItems.END_STONE_LEGGINGS, "末地石护腿");
        translationBuilder.add(ModItems.END_STONE_BOOTS, "末地石鞋子");
        translationBuilder.add(ModItems.DIORITE_HELMET, "闪长岩头盔");
        translationBuilder.add(ModItems.DIORITE_CHESTPLATE, "闪长岩胸甲");
        translationBuilder.add(ModItems.DIORITE_LEGGINGS, "闪长岩护腿");
        translationBuilder.add(ModItems.DIORITE_BOOTS, "闪长岩鞋子");
        translationBuilder.add(ModItems.GRANITE_HELMET, "花岗岩头盔");
        translationBuilder.add(ModItems.GRANITE_CHESTPLATE, "花岗岩胸甲");
        translationBuilder.add(ModItems.GRANITE_LEGGINGS, "花岗岩护腿");
        translationBuilder.add(ModItems.GRANITE_BOOTS, "花岗岩鞋子");
        translationBuilder.add(ModItems.ANDESITE_HELMET, "安山岩头盔");
        translationBuilder.add(ModItems.ANDESITE_CHESTPLATE, "安山岩胸甲");
        translationBuilder.add(ModItems.ANDESITE_LEGGINGS, "安山岩护腿");
        translationBuilder.add(ModItems.ANDESITE_BOOTS, "安山岩鞋子");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_HELMET, "哭泣的黑曜石头盔");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_CHESTPLATE, "哭泣的黑曜石胸甲");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_LEGGINGS, "哭泣的黑曜石护腿");
        translationBuilder.add(ModItems.CRYING_OBSIDIAN_BOOTS, "哭泣的黑曜石鞋子");
        translationBuilder.add(ModItems.OBSIDIAN_HELMET, "黑曜石头盔");
        translationBuilder.add(ModItems.OBSIDIAN_CHESTPLATE, "黑曜石胸甲");
        translationBuilder.add(ModItems.OBSIDIAN_LEGGINGS, "黑曜石护腿");
        translationBuilder.add(ModItems.OBSIDIAN_BOOTS, "黑曜石鞋子");
    }
}
