package com.ind.mod.item;

import com.ind.mod.StoneWoodIndustry;
import com.ind.mod.materials.ModArmorMaterials;
import com.ind.mod.materials.ModToolMaterials;
import net.fabricmc.fabric.api.item.v1.FabricItemSettings;
import net.minecraft.item.*;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;

public class ModItems {
    public static void registerModItems(){
        StoneWoodIndustry.LOGGER.info("Stone&Wood Industry>>>Registering Mod Items!");
    }

    public static Item register(String name, Item item){
        return Registry.register(Registries.ITEM, new Identifier(StoneWoodIndustry.MOD_ID, name), item);
    }
    // FUCK MOJANG
    public static final Item STONE_HELMET = register("stone_helmet", new StoneArmorItem(ModArmorMaterials.STONE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item STONE_CHESTPLATE = register("stone_chestplate", new StoneArmorItem(ModArmorMaterials.STONE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item STONE_LEGGINGS = register("stone_leggings", new StoneArmorItem(ModArmorMaterials.STONE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item STONE_BOOTS = register("stone_boots", new StoneArmorItem(ModArmorMaterials.STONE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_HELMET = register("smooth_stone_helmet", new SmoothStoneArmorItem(ModArmorMaterials.SMOOTH_STONE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_CHESTPLATE = register("smooth_stone_chestplate", new SmoothStoneArmorItem(ModArmorMaterials.SMOOTH_STONE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_LEGGINGS = register("smooth_stone_leggings", new SmoothStoneArmorItem(ModArmorMaterials.SMOOTH_STONE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_BOOTS = register("smooth_stone_boots", new SmoothStoneArmorItem(ModArmorMaterials.SMOOTH_STONE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_PICKAXE = register("smooth_stone_pickaxe", new PickaxeItem(ModToolMaterials.SMOOTH_STONE, 1, -2.8F, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_SWORD = register("smooth_stone_sword", new SwordItem(ModToolMaterials.SMOOTH_STONE, 3, -2.4F, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_HOE = register("smooth_stone_hoe", new HoeItem(ModToolMaterials.SMOOTH_STONE, -1, -2.0F, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_AXE = register("smooth_stone_axe", new AxeItem(ModToolMaterials.SMOOTH_STONE, 7, -3.2F, new FabricItemSettings()));
    public static final Item SMOOTH_STONE_SHOVEL = register("smooth_stone_shovel", new ShovelItem(ModToolMaterials.SMOOTH_STONE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item OAK_HELMET = register("oak_helmet", new WoodArmorItem(ModArmorMaterials.OAK, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item OAK_CHESTPLATE = register("oak_chestplate", new WoodArmorItem(ModArmorMaterials.OAK, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item OAK_LEGGINGS = register("oak_leggings", new WoodArmorItem(ModArmorMaterials.OAK, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item OAK_BOOTS = register("oak_boots", new WoodArmorItem(ModArmorMaterials.OAK, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item SPRUCE_HELMET = register("spruce_helmet", new WoodArmorItem(ModArmorMaterials.SPRUCE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item SPRUCE_CHESTPLATE = register("spruce_chestplate", new WoodArmorItem(ModArmorMaterials.SPRUCE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item SPRUCE_LEGGINGS = register("spruce_leggings", new WoodArmorItem(ModArmorMaterials.SPRUCE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item SPRUCE_BOOTS = register("spruce_boots", new WoodArmorItem(ModArmorMaterials.SPRUCE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item BIRCH_HELMET = register("birch_helmet", new WoodArmorItem(ModArmorMaterials.BIRCH, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item BIRCH_CHESTPLATE = register("birch_chestplate", new WoodArmorItem(ModArmorMaterials.BIRCH, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item BIRCH_LEGGINGS = register("birch_leggings", new WoodArmorItem(ModArmorMaterials.BIRCH, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item BIRCH_BOOTS = register("birch_boots", new WoodArmorItem(ModArmorMaterials.BIRCH, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item JUNGLE_HELMET = register("jungle_helmet", new WoodArmorItem(ModArmorMaterials.JUNGLE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item JUNGLE_CHESTPLATE = register("jungle_chestplate", new WoodArmorItem(ModArmorMaterials.JUNGLE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item JUNGLE_LEGGINGS = register("jungle_leggings", new WoodArmorItem(ModArmorMaterials.JUNGLE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item JUNGLE_BOOTS = register("jungle_boots", new WoodArmorItem(ModArmorMaterials.JUNGLE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item ACACIA_HELMET = register("acacia_helmet", new WoodArmorItem(ModArmorMaterials.ACACIA, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item ACACIA_CHESTPLATE = register("acacia_chestplate", new WoodArmorItem(ModArmorMaterials.ACACIA, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item ACACIA_LEGGINGS = register("acacia_leggings", new WoodArmorItem(ModArmorMaterials.ACACIA, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item ACACIA_BOOTS = register("acacia_boots", new WoodArmorItem(ModArmorMaterials.ACACIA, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item DARK_OAK_HELMET = register("dark_oak_helmet", new WoodArmorItem(ModArmorMaterials.DARK_OAK, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item DARK_OAK_CHESTPLATE = register("dark_oak_chestplate", new WoodArmorItem(ModArmorMaterials.DARK_OAK, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item DARK_OAK_LEGGINGS = register("dark_oak_leggings", new WoodArmorItem(ModArmorMaterials.DARK_OAK, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item DARK_OAK_BOOTS = register("dark_oak_boots", new WoodArmorItem(ModArmorMaterials.DARK_OAK, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item MANGROVE_HELMET = register("mangrove_helmet", new WoodArmorItem(ModArmorMaterials.MANGROVE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item MANGROVE_CHESTPLATE = register("mangrove_chestplate", new WoodArmorItem(ModArmorMaterials.MANGROVE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item MANGROVE_LEGGINGS = register("mangrove_leggings", new WoodArmorItem(ModArmorMaterials.MANGROVE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item MANGROVE_BOOTS = register("mangrove_boots", new WoodArmorItem(ModArmorMaterials.MANGROVE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item CHERRY_HELMET = register("cherry_helmet", new WoodArmorItem(ModArmorMaterials.CHERRY, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item CHERRY_CHESTPLATE = register("cherry_chestplate", new WoodArmorItem(ModArmorMaterials.CHERRY, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item CHERRY_LEGGINGS = register("cherry_leggings", new WoodArmorItem(ModArmorMaterials.CHERRY, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item CHERRY_BOOTS = register("cherry_boots", new WoodArmorItem(ModArmorMaterials.CHERRY, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item BLACKSTONE_HELMET = register("blackstone_helmet", new StoneArmorItem(ModArmorMaterials.BLACKSTONE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item BLACKSTONE_CHESTPLATE = register("blackstone_chestplate", new StoneArmorItem(ModArmorMaterials.BLACKSTONE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item BLACKSTONE_LEGGINGS = register("blackstone_leggings", new StoneArmorItem(ModArmorMaterials.BLACKSTONE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item BLACKSTONE_BOOTS = register("blackstone_boots", new StoneArmorItem(ModArmorMaterials.BLACKSTONE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item DEEPSLATE_HELMET = register("deepslate_helmet", new StoneArmorItem(ModArmorMaterials.DEEPSLATE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item DEEPSLATE_CHESTPLATE = register("deepslate_chestplate", new StoneArmorItem(ModArmorMaterials.DEEPSLATE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item DEEPSLATE_LEGGINGS = register("deepslate_leggings", new StoneArmorItem(ModArmorMaterials.DEEPSLATE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item DEEPSLATE_BOOTS = register("deepslate_boots", new StoneArmorItem(ModArmorMaterials.DEEPSLATE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item CRIMSON_HELMET = register("crimson_helmet", new WoodArmorItem(ModArmorMaterials.CRIMSON, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item CRIMSON_CHESTPLATE = register("crimson_chestplate", new WoodArmorItem(ModArmorMaterials.CRIMSON, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item CRIMSON_LEGGINGS = register("crimson_leggings", new WoodArmorItem(ModArmorMaterials.CRIMSON, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item CRIMSON_BOOTS = register("crimson_boots", new WoodArmorItem(ModArmorMaterials.CRIMSON, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item WARPED_HELMET = register("warped_helmet", new WoodArmorItem(ModArmorMaterials.WARPED, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item WARPED_CHESTPLATE = register("warped_chestplate", new WoodArmorItem(ModArmorMaterials.WARPED, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item WARPED_LEGGINGS = register("warped_leggings", new WoodArmorItem(ModArmorMaterials.WARPED, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item WARPED_BOOTS = register("warped_boots", new WoodArmorItem(ModArmorMaterials.WARPED, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item BAMBOO_HELMET = register("bamboo_helmet", new WoodArmorItem(ModArmorMaterials.BAMBOO, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item BAMBOO_CHESTPLATE = register("bamboo_chestplate", new WoodArmorItem(ModArmorMaterials.BAMBOO, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item BAMBOO_LEGGINGS = register("bamboo_leggings", new WoodArmorItem(ModArmorMaterials.BAMBOO, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item BAMBOO_BOOTS = register("bamboo_boots", new WoodArmorItem(ModArmorMaterials.BAMBOO, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item NETHERRACK_HELMET = register("netherrack_helmet", new StoneArmorItem(ModArmorMaterials.NETHERRACK, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item NETHERRACK_CHESTPLATE = register("netherrack_chestplate", new StoneArmorItem(ModArmorMaterials.NETHERRACK, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item NETHERRACK_LEGGINGS = register("netherrack_leggings", new StoneArmorItem(ModArmorMaterials.NETHERRACK, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item NETHERRACK_BOOTS = register("netherrack_boots", new StoneArmorItem(ModArmorMaterials.NETHERRACK, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item BASALT_HELMET = register("basalt_helmet", new StoneArmorItem(ModArmorMaterials.BASALT, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item BASALT_CHESTPLATE = register("basalt_chestplate", new StoneArmorItem(ModArmorMaterials.BASALT, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item BASALT_LEGGINGS = register("basalt_leggings", new StoneArmorItem(ModArmorMaterials.BASALT, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item BASALT_BOOTS = register("basalt_boots", new StoneArmorItem(ModArmorMaterials.BASALT, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item END_STONE_HELMET = register("end_stone_helmet", new StoneArmorItem(ModArmorMaterials.END_STONE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item END_STONE_CHESTPLATE = register("end_stone_chestplate", new StoneArmorItem(ModArmorMaterials.END_STONE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item END_STONE_LEGGINGS = register("end_stone_leggings", new StoneArmorItem(ModArmorMaterials.END_STONE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item END_STONE_BOOTS = register("end_stone_boots", new StoneArmorItem(ModArmorMaterials.END_STONE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item DIORITE_HELMET = register("diorite_helmet", new StoneArmorItem(ModArmorMaterials.DIORITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item DIORITE_CHESTPLATE = register("diorite_chestplate", new StoneArmorItem(ModArmorMaterials.DIORITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item DIORITE_LEGGINGS = register("diorite_leggings", new StoneArmorItem(ModArmorMaterials.DIORITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item DIORITE_BOOTS = register("diorite_boots", new StoneArmorItem(ModArmorMaterials.DIORITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item GRANITE_HELMET = register("granite_helmet", new StoneArmorItem(ModArmorMaterials.GRANITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item GRANITE_CHESTPLATE = register("granite_chestplate", new StoneArmorItem(ModArmorMaterials.GRANITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item GRANITE_LEGGINGS = register("granite_leggings", new StoneArmorItem(ModArmorMaterials.GRANITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item GRANITE_BOOTS = register("granite_boots", new StoneArmorItem(ModArmorMaterials.GRANITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item ANDESITE_HELMET = register("andesite_helmet", new StoneArmorItem(ModArmorMaterials.ANDESITE, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item ANDESITE_CHESTPLATE = register("andesite_chestplate", new StoneArmorItem(ModArmorMaterials.ANDESITE, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item ANDESITE_LEGGINGS = register("andesite_leggings", new StoneArmorItem(ModArmorMaterials.ANDESITE, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item ANDESITE_BOOTS = register("andesite_boots", new StoneArmorItem(ModArmorMaterials.ANDESITE, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_HELMET = register("crying_obsidian_helmet", new StoneArmorItem(ModArmorMaterials.CRYING_OBSIDIAN, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_CHESTPLATE = register("crying_obsidian_chestplate", new StoneArmorItem(ModArmorMaterials.CRYING_OBSIDIAN, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_LEGGINGS = register("crying_obsidian_leggings", new StoneArmorItem(ModArmorMaterials.CRYING_OBSIDIAN, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_BOOTS = register("crying_obsidian_boots", new StoneArmorItem(ModArmorMaterials.CRYING_OBSIDIAN, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item OBSIDIAN_HELMET = register("obsidian_helmet", new StoneArmorItem(ModArmorMaterials.OBSIDIAN, ArmorItem.Type.HELMET, new FabricItemSettings()));
    public static final Item OBSIDIAN_CHESTPLATE = register("obsidian_chestplate", new StoneArmorItem(ModArmorMaterials.OBSIDIAN, ArmorItem.Type.CHESTPLATE, new FabricItemSettings()));
    public static final Item OBSIDIAN_LEGGINGS = register("obsidian_leggings", new StoneArmorItem(ModArmorMaterials.OBSIDIAN, ArmorItem.Type.LEGGINGS, new FabricItemSettings()));
    public static final Item OBSIDIAN_BOOTS = register("obsidian_boots", new StoneArmorItem(ModArmorMaterials.OBSIDIAN, ArmorItem.Type.BOOTS, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_PICKAXE = register("crying_obsidian_pickaxe", new PickaxeItem(ModToolMaterials.CRYING_OBSIDIAN, 1, -2.8F, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_SWORD = register("crying_obsidian_sword", new SwordItem(ModToolMaterials.CRYING_OBSIDIAN, 3, -2.4F, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_HOE = register("crying_obsidian_hoe", new HoeItem(ModToolMaterials.CRYING_OBSIDIAN, -1, -2.0F, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_AXE = register("crying_obsidian_axe", new AxeItem(ModToolMaterials.CRYING_OBSIDIAN, 7, -3.2F, new FabricItemSettings()));
    public static final Item CRYING_OBSIDIAN_SHOVEL = register("crying_obsidian_shovel", new ShovelItem(ModToolMaterials.CRYING_OBSIDIAN, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item OBSIDIAN_PICKAXE = register("obsidian_pickaxe", new PickaxeItem(ModToolMaterials.OBSIDIAN, 1, -2.8F, new FabricItemSettings()));
    public static final Item OBSIDIAN_SWORD = register("obsidian_sword", new SwordItem(ModToolMaterials.OBSIDIAN, 3, -2.4F, new FabricItemSettings()));
    public static final Item OBSIDIAN_HOE = register("obsidian_hoe", new HoeItem(ModToolMaterials.OBSIDIAN, -1, -2.0F, new FabricItemSettings()));
    public static final Item OBSIDIAN_AXE = register("obsidian_axe", new AxeItem(ModToolMaterials.OBSIDIAN, 7, -3.2F, new FabricItemSettings()));
    public static final Item OBSIDIAN_SHOVEL = register("obsidian_shovel", new ShovelItem(ModToolMaterials.OBSIDIAN, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item END_STONE_PICKAXE = register("end_stone_pickaxe", new PickaxeItem(ModToolMaterials.END_STONE, 1, -2.8F, new FabricItemSettings()));
    public static final Item END_STONE_SWORD = register("end_stone_sword", new SwordItem(ModToolMaterials.END_STONE, 3, -2.4F, new FabricItemSettings()));
    public static final Item END_STONE_HOE = register("end_stone_hoe", new HoeItem(ModToolMaterials.END_STONE, -1, -2.0F, new FabricItemSettings()));
    public static final Item END_STONE_AXE = register("end_stone_axe", new AxeItem(ModToolMaterials.END_STONE, 7, -3.2F, new FabricItemSettings()));
    public static final Item END_STONE_SHOVEL = register("end_stone_shovel", new ShovelItem(ModToolMaterials.END_STONE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item BLACKSTONE_PICKAXE = register("blackstone_pickaxe", new PickaxeItem(ModToolMaterials.BLACKSTONE, 1, -2.8F, new FabricItemSettings()));
    public static final Item BLACKSTONE_SWORD = register("blackstone_sword", new SwordItem(ModToolMaterials.BLACKSTONE, 3, -2.4F, new FabricItemSettings()));
    public static final Item BLACKSTONE_HOE = register("blackstone_hoe", new HoeItem(ModToolMaterials.BLACKSTONE, -1, -2.0F, new FabricItemSettings()));
    public static final Item BLACKSTONE_AXE = register("blackstone_axe", new AxeItem(ModToolMaterials.BLACKSTONE, 7, -3.2F, new FabricItemSettings()));
    public static final Item BLACKSTONE_SHOVEL = register("blackstone_shovel", new ShovelItem(ModToolMaterials.BLACKSTONE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item DEEPSLATE_PICKAXE = register("deepslate_pickaxe", new PickaxeItem(ModToolMaterials.DEEPSLATE, 1, -2.8F, new FabricItemSettings()));
    public static final Item DEEPSLATE_SWORD = register("deepslate_sword", new SwordItem(ModToolMaterials.DEEPSLATE, 3, -2.4F, new FabricItemSettings()));
    public static final Item DEEPSLATE_HOE = register("deepslate_hoe", new HoeItem(ModToolMaterials.DEEPSLATE, -1, -2.0F, new FabricItemSettings()));
    public static final Item DEEPSLATE_AXE = register("deepslate_axe", new AxeItem(ModToolMaterials.DEEPSLATE, 7, -3.2F, new FabricItemSettings()));
    public static final Item DEEPSLATE_SHOVEL = register("deepslate_shovel", new ShovelItem(ModToolMaterials.DEEPSLATE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item NETHERRACK_PICKAXE = register("netherrack_pickaxe", new PickaxeItem(ModToolMaterials.NETHERRACK, 1, -2.8F, new FabricItemSettings()));
    public static final Item NETHERRACK_SWORD = register("netherrack_sword", new SwordItem(ModToolMaterials.NETHERRACK, 3, -2.4F, new FabricItemSettings()));
    public static final Item NETHERRACK_HOE = register("netherrack_hoe", new HoeItem(ModToolMaterials.NETHERRACK, -1, -2.0F, new FabricItemSettings()));
    public static final Item NETHERRACK_AXE = register("netherrack_axe", new AxeItem(ModToolMaterials.NETHERRACK, 7, -3.2F, new FabricItemSettings()));
    public static final Item NETHERRACK_SHOVEL = register("netherrack_shovel", new ShovelItem(ModToolMaterials.NETHERRACK, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item DIORITE_PICKAXE = register("diorite_pickaxe", new PickaxeItem(ModToolMaterials.DIORITE, 1, -2.8F, new FabricItemSettings()));
    public static final Item DIORITE_SWORD = register("diorite_sword", new SwordItem(ModToolMaterials.DIORITE, 3, -2.4F, new FabricItemSettings()));
    public static final Item DIORITE_HOE = register("diorite_hoe", new HoeItem(ModToolMaterials.DIORITE, -1, -2.0F, new FabricItemSettings()));
    public static final Item DIORITE_AXE = register("diorite_axe", new AxeItem(ModToolMaterials.DIORITE, 7, -3.2F, new FabricItemSettings()));
    public static final Item DIORITE_SHOVEL = register("diorite_shovel", new ShovelItem(ModToolMaterials.DIORITE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item GRANITE_PICKAXE = register("granite_pickaxe", new PickaxeItem(ModToolMaterials.GRANITE, 1, -2.8F, new FabricItemSettings()));
    public static final Item GRANITE_SWORD = register("granite_sword", new SwordItem(ModToolMaterials.GRANITE, 3, -2.4F, new FabricItemSettings()));
    public static final Item GRANITE_HOE = register("granite_hoe", new HoeItem(ModToolMaterials.GRANITE, -1, -2.2F, new FabricItemSettings()));
    public static final Item GRANITE_AXE = register("granite_axe", new AxeItem(ModToolMaterials.GRANITE, 7, -3.2F, new FabricItemSettings()));
    public static final Item GRANITE_SHOVEL = register("granite_shovel", new ShovelItem(ModToolMaterials.GRANITE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item ANDESITE_PICKAXE = register("andesite_pickaxe", new PickaxeItem(ModToolMaterials.ANDESITE, 1, -2.8F, new FabricItemSettings()));
    public static final Item ANDESITE_SWORD = register("andesite_sword", new SwordItem(ModToolMaterials.ANDESITE, 3, -2.4F, new FabricItemSettings()));
    public static final Item ANDESITE_HOE = register("andesite_hoe", new HoeItem(ModToolMaterials.ANDESITE, -1, -2.0F, new FabricItemSettings()));
    public static final Item ANDESITE_AXE = register("andesite_axe", new AxeItem(ModToolMaterials.ANDESITE, 7, -3.2F, new FabricItemSettings()));
    public static final Item ANDESITE_SHOVEL = register("andesite_shovel", new ShovelItem(ModToolMaterials.ANDESITE, 1.5F, -3.0F, new FabricItemSettings()));
    public static final Item BASALT_PICKAXE = register("basalt_pickaxe", new PickaxeItem(ModToolMaterials.BASALT, 1, -2.8F, new FabricItemSettings()));
    public static final Item BASALT_SWORD = register("basalt_sword", new SwordItem(ModToolMaterials.BASALT, 3, -2.4F, new FabricItemSettings()));
    public static final Item BASALT_HOE = register("basalt_hoe", new HoeItem(ModToolMaterials.BASALT, -1, -2.0F, new FabricItemSettings()));
    public static final Item BASALT_AXE = register("basalt_axe", new AxeItem(ModToolMaterials.BASALT, 7, -3.2F, new FabricItemSettings()));
    public static final Item BASALT_SHOVEL = register("basalt_shovel", new ShovelItem(ModToolMaterials.BASALT, 1.5F, -3.0F, new FabricItemSettings()));
}
