package com.ind.mod.inventory;

import com.ind.mod.StoneWoodIndustry;
import com.ind.mod.block.ModBlocks;
import com.ind.mod.enchantment.ModEnchantment;
import com.ind.mod.item.ModItems;
import net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup;
import net.minecraft.block.Blocks;
import net.minecraft.enchantment.EnchantmentLevelEntry;
import net.minecraft.item.EnchantedBookItem;
import net.minecraft.item.ItemGroup;
import net.minecraft.item.ItemStack;
import net.minecraft.item.Items;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.text.Text;
import net.minecraft.util.Identifier;

public class ModItemGroups {
     public static void register(){
         StoneWoodIndustry.LOGGER.info("STONE&WOOD INDUSTRY>>>Registering MOD Itemgroups!");
     }

    public static ItemGroup register(String name, ItemGroup itemGroup){
        return Registry.register(Registries.ITEM_GROUP, new Identifier(StoneWoodIndustry.MOD_ID, name), itemGroup);
    }
    public static final ItemGroup STONE_WOOD_INDUSTRY_ENCHANTMENT = register("stone_wood_industry_enchant", FabricItemGroup.builder()
            .displayName(Text.translatable(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_enchant").toTranslationKey()))
            .icon(()->new ItemStack(Items.ENCHANTED_BOOK))
            .entries(((displayContext, entries) -> {
                entries.add(EnchantedBookItem.forEnchantment(new EnchantmentLevelEntry(ModEnchantment.HARDEN, 5)));
                entries.add(EnchantedBookItem.forEnchantment(new EnchantmentLevelEntry(ModEnchantment.SPEED, 5)));
                entries.add(EnchantedBookItem.forEnchantment(new EnchantmentLevelEntry(ModEnchantment.UNDYING, 10)));
            })).build());
    public static final ItemGroup STONE_WOOD_INDUSTRY_STONE = register("stone_wood_industry_stone", FabricItemGroup.builder()
            .displayName(Text.translatable(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_stone").toTranslationKey()))
            .icon(()->new ItemStack(Items.SMOOTH_STONE))
            .entries(((displayContext, entries) -> {
                entries.add(ModItems.STONE_HELMET);
                entries.add(ModItems.STONE_CHESTPLATE);
                entries.add(ModItems.STONE_LEGGINGS);
                entries.add(ModItems.STONE_BOOTS);
                entries.add(Items.STONE_SWORD);
                entries.add(Items.STONE_SHOVEL);
                entries.add(Items.STONE_PICKAXE);
                entries.add(Items.STONE_AXE);
                entries.add(Items.STONE_HOE);
                entries.add(ModItems.SMOOTH_STONE_HELMET);
                entries.add(ModItems.SMOOTH_STONE_CHESTPLATE);
                entries.add(ModItems.SMOOTH_STONE_LEGGINGS);
                entries.add(ModItems.SMOOTH_STONE_BOOTS);
                entries.add(ModItems.SMOOTH_STONE_SWORD);
                entries.add(ModItems.SMOOTH_STONE_SHOVEL);
                entries.add(ModItems.SMOOTH_STONE_PICKAXE);
                entries.add(ModItems.SMOOTH_STONE_AXE);
                entries.add(ModItems.SMOOTH_STONE_HOE);
                entries.add(ModItems.BLACKSTONE_HELMET);
                entries.add(ModItems.BLACKSTONE_CHESTPLATE);
                entries.add(ModItems.BLACKSTONE_LEGGINGS);
                entries.add(ModItems.BLACKSTONE_BOOTS);
                entries.add(ModItems.BLACKSTONE_SWORD);
                entries.add(ModItems.BLACKSTONE_SHOVEL);
                entries.add(ModItems.BLACKSTONE_PICKAXE);
                entries.add(ModItems.BLACKSTONE_AXE);
                entries.add(ModItems.BLACKSTONE_HOE);
                entries.add(ModItems.DEEPSLATE_HELMET);
                entries.add(ModItems.DEEPSLATE_CHESTPLATE);
                entries.add(ModItems.DEEPSLATE_LEGGINGS);
                entries.add(ModItems.DEEPSLATE_BOOTS);
                entries.add(ModItems.DEEPSLATE_SWORD);
                entries.add(ModItems.DEEPSLATE_SHOVEL);
                entries.add(ModItems.DEEPSLATE_PICKAXE);
                entries.add(ModItems.DEEPSLATE_AXE);
                entries.add(ModItems.DEEPSLATE_HOE);
                entries.add(ModItems.NETHERRACK_HELMET);
                entries.add(ModItems.NETHERRACK_CHESTPLATE);
                entries.add(ModItems.NETHERRACK_LEGGINGS);
                entries.add(ModItems.NETHERRACK_BOOTS);
                entries.add(ModItems.NETHERRACK_SWORD);
                entries.add(ModItems.NETHERRACK_SHOVEL);
                entries.add(ModItems.NETHERRACK_PICKAXE);
                entries.add(ModItems.NETHERRACK_AXE);
                entries.add(ModItems.NETHERRACK_HOE);
                entries.add(ModItems.BASALT_HELMET);
                entries.add(ModItems.BASALT_CHESTPLATE);
                entries.add(ModItems.BASALT_LEGGINGS);
                entries.add(ModItems.BASALT_BOOTS);
                entries.add(ModItems.BASALT_SWORD);
                entries.add(ModItems.BASALT_SHOVEL);
                entries.add(ModItems.BASALT_PICKAXE);
                entries.add(ModItems.BASALT_AXE);
                entries.add(ModItems.BASALT_HOE);
                entries.add(ModItems.END_STONE_HELMET);
                entries.add(ModItems.END_STONE_CHESTPLATE);
                entries.add(ModItems.END_STONE_LEGGINGS);
                entries.add(ModItems.END_STONE_BOOTS);
                entries.add(ModItems.END_STONE_SWORD);
                entries.add(ModItems.END_STONE_SHOVEL);
                entries.add(ModItems.END_STONE_PICKAXE);
                entries.add(ModItems.END_STONE_AXE);
                entries.add(ModItems.END_STONE_HOE);
                entries.add(ModItems.DIORITE_HELMET);
                entries.add(ModItems.DIORITE_CHESTPLATE);
                entries.add(ModItems.DIORITE_LEGGINGS);
                entries.add(ModItems.DIORITE_BOOTS);
                entries.add(ModItems.DIORITE_SWORD);
                entries.add(ModItems.DIORITE_SHOVEL);
                entries.add(ModItems.DIORITE_PICKAXE);
                entries.add(ModItems.DIORITE_AXE);
                entries.add(ModItems.DIORITE_HOE);
                entries.add(ModItems.GRANITE_HELMET);
                entries.add(ModItems.GRANITE_CHESTPLATE);
                entries.add(ModItems.GRANITE_LEGGINGS);
                entries.add(ModItems.GRANITE_BOOTS);
                entries.add(ModItems.GRANITE_SWORD);
                entries.add(ModItems.GRANITE_SHOVEL);
                entries.add(ModItems.GRANITE_PICKAXE);
                entries.add(ModItems.GRANITE_AXE);
                entries.add(ModItems.GRANITE_HOE);
                entries.add(ModItems.ANDESITE_HELMET);
                entries.add(ModItems.ANDESITE_CHESTPLATE);
                entries.add(ModItems.ANDESITE_LEGGINGS);
                entries.add(ModItems.ANDESITE_BOOTS);
                entries.add(ModItems.ANDESITE_SWORD);
                entries.add(ModItems.ANDESITE_SHOVEL);
                entries.add(ModItems.ANDESITE_PICKAXE);
                entries.add(ModItems.ANDESITE_AXE);
                entries.add(ModItems.ANDESITE_HOE);
                entries.add(ModItems.CRYING_OBSIDIAN_HELMET);
                entries.add(ModItems.CRYING_OBSIDIAN_CHESTPLATE);
                entries.add(ModItems.CRYING_OBSIDIAN_LEGGINGS);
                entries.add(ModItems.CRYING_OBSIDIAN_BOOTS);
                entries.add(ModItems.CRYING_OBSIDIAN_SWORD);
                entries.add(ModItems.CRYING_OBSIDIAN_SHOVEL);
                entries.add(ModItems.CRYING_OBSIDIAN_PICKAXE);
                entries.add(ModItems.CRYING_OBSIDIAN_AXE);
                entries.add(ModItems.CRYING_OBSIDIAN_HOE);
                entries.add(ModItems.OBSIDIAN_HELMET);
                entries.add(ModItems.OBSIDIAN_CHESTPLATE);
                entries.add(ModItems.OBSIDIAN_LEGGINGS);
                entries.add(ModItems.OBSIDIAN_BOOTS);
                entries.add(ModItems.OBSIDIAN_SWORD);
                entries.add(ModItems.OBSIDIAN_SHOVEL);
                entries.add(ModItems.OBSIDIAN_PICKAXE);
                entries.add(ModItems.OBSIDIAN_AXE);
                entries.add(ModItems.OBSIDIAN_HOE);
                entries.add(Blocks.SMOOTH_STONE);
                entries.add(Blocks.SMOOTH_STONE_SLAB);
                entries.add(ModBlocks.SMOOTH_STONE_STAIRS);
                entries.add(ModBlocks.SMOOTH_STONE_PRESSURE_PLATE);
                entries.add(ModBlocks.SMOOTH_STONE_BUTTON);
                entries.add(ModBlocks.OBSIDIAN_SLAB);
                entries.add(ModBlocks.OBSIDIAN_STAIRS);
            })).build());
    public static final ItemGroup STONE_WOOD_INDUSTRY_WOOD = register("stone_wood_industry_wood", FabricItemGroup.builder()
            .displayName(Text.translatable(new Identifier(StoneWoodIndustry.MOD_ID, "stone_wood_industry_wood").toTranslationKey()))
            .icon(()->new ItemStack(Items.OAK_LOG))
            .entries(((displayContext, entries) -> {
                entries.add(ModItems.OAK_HELMET);
                entries.add(ModItems.OAK_CHESTPLATE);
                entries.add(ModItems.OAK_LEGGINGS);
                entries.add(ModItems.OAK_BOOTS);
                entries.add(ModItems.OAK_SWORD);
                entries.add(ModItems.OAK_SHOVEL);
                entries.add(ModItems.OAK_PICKAXE);
                entries.add(ModItems.OAK_HOE);
                entries.add(ModItems.OAK_AXE);
                entries.add(ModItems.SPRUCE_HELMET);
                entries.add(ModItems.SPRUCE_CHESTPLATE);
                entries.add(ModItems.SPRUCE_LEGGINGS);
                entries.add(ModItems.SPRUCE_BOOTS);
                entries.add(ModItems.SPRUCE_SWORD);
                entries.add(ModItems.SPRUCE_SHOVEL);
                entries.add(ModItems.SPRUCE_PICKAXE);
                entries.add(ModItems.SPRUCE_HOE);
                entries.add(ModItems.SPRUCE_AXE);
                entries.add(ModItems.BIRCH_HELMET);
                entries.add(ModItems.BIRCH_CHESTPLATE);
                entries.add(ModItems.BIRCH_LEGGINGS);
                entries.add(ModItems.BIRCH_BOOTS);
                entries.add(ModItems.BIRCH_SWORD);
                entries.add(ModItems.BIRCH_SHOVEL);
                entries.add(ModItems.BIRCH_PICKAXE);
                entries.add(ModItems.BIRCH_HOE);
                entries.add(ModItems.BIRCH_AXE);
                entries.add(ModItems.ACACIA_HELMET);
                entries.add(ModItems.ACACIA_CHESTPLATE);
                entries.add(ModItems.ACACIA_LEGGINGS);
                entries.add(ModItems.ACACIA_BOOTS);
                entries.add(ModItems.ACACIA_SWORD);
                entries.add(ModItems.ACACIA_SHOVEL);
                entries.add(ModItems.ACACIA_PICKAXE);
                entries.add(ModItems.ACACIA_HOE);
                entries.add(ModItems.ACACIA_AXE);
                entries.add(ModItems.JUNGLE_HELMET);
                entries.add(ModItems.JUNGLE_CHESTPLATE);
                entries.add(ModItems.JUNGLE_LEGGINGS);
                entries.add(ModItems.JUNGLE_BOOTS);
                entries.add(ModItems.JUNGLE_SWORD);
                entries.add(ModItems.JUNGLE_SHOVEL);
                entries.add(ModItems.JUNGLE_PICKAXE);
                entries.add(ModItems.JUNGLE_HOE);
                entries.add(ModItems.JUNGLE_AXE);
                entries.add(ModItems.DARK_OAK_HELMET);
                entries.add(ModItems.DARK_OAK_CHESTPLATE);
                entries.add(ModItems.DARK_OAK_LEGGINGS);
                entries.add(ModItems.DARK_OAK_BOOTS);
                entries.add(ModItems.DARK_OAK_SWORD);
                entries.add(ModItems.DARK_OAK_SHOVEL);
                entries.add(ModItems.DARK_OAK_PICKAXE);
                entries.add(ModItems.DARK_OAK_HOE);
                entries.add(ModItems.DARK_OAK_AXE);
                entries.add(ModItems.MANGROVE_HELMET);
                entries.add(ModItems.MANGROVE_CHESTPLATE);
                entries.add(ModItems.MANGROVE_LEGGINGS);
                entries.add(ModItems.MANGROVE_BOOTS);
                entries.add(ModItems.MANGROVE_SWORD);
                entries.add(ModItems.MANGROVE_SHOVEL);
                entries.add(ModItems.MANGROVE_PICKAXE);
                entries.add(ModItems.MANGROVE_HOE);
                entries.add(ModItems.MANGROVE_AXE);
                entries.add(ModItems.CHERRY_HELMET);
                entries.add(ModItems.CHERRY_CHESTPLATE);
                entries.add(ModItems.CHERRY_LEGGINGS);
                entries.add(ModItems.CHERRY_BOOTS);
                entries.add(ModItems.CHERRY_SWORD);
                entries.add(ModItems.CHERRY_SHOVEL);
                entries.add(ModItems.CHERRY_PICKAXE);
                entries.add(ModItems.CHERRY_HOE);
                entries.add(ModItems.CHERRY_AXE);
                entries.add(ModItems.BAMBOO_HELMET);
                entries.add(ModItems.BAMBOO_CHESTPLATE);
                entries.add(ModItems.BAMBOO_LEGGINGS);
                entries.add(ModItems.BAMBOO_BOOTS);
                entries.add(ModItems.BAMBOO_SWORD);
                entries.add(ModItems.BAMBOO_SHOVEL);
                entries.add(ModItems.BAMBOO_PICKAXE);
                entries.add(ModItems.BAMBOO_HOE);
                entries.add(ModItems.BAMBOO_AXE);
                entries.add(ModItems.WARPED_HELMET);
                entries.add(ModItems.WARPED_CHESTPLATE);
                entries.add(ModItems.WARPED_LEGGINGS);
                entries.add(ModItems.WARPED_BOOTS);
                entries.add(ModItems.WARPED_SWORD);
                entries.add(ModItems.WARPED_SHOVEL);
                entries.add(ModItems.WARPED_PICKAXE);
                entries.add(ModItems.WARPED_HOE);
                entries.add(ModItems.WARPED_AXE);
                entries.add(ModItems.CRIMSON_HELMET);
                entries.add(ModItems.CRIMSON_CHESTPLATE);
                entries.add(ModItems.CRIMSON_LEGGINGS);
                entries.add(ModItems.CRIMSON_BOOTS);
                entries.add(ModItems.CRIMSON_SWORD);
                entries.add(ModItems.CRIMSON_SHOVEL);
                entries.add(ModItems.CRIMSON_PICKAXE);
                entries.add(ModItems.CRIMSON_HOE);
                entries.add(ModItems.CRIMSON_AXE);
            })).build());
}
